# -*- coding: utf-8 -*-
"""convert_to_canonical_smiles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AI1m85tGtEzcURImDTnltgyRCwmmhVo9
"""

!pip install rdkit
from rdkit import Chem

def convert_to_canonical_smiles(smiles_list):
    """
    Converts a list of SMILES strings to their canonical form.

    Parameters:
        smiles_list (list of str): List of SMILES strings to be converted.

    Returns:
        list of str: List of canonical SMILES strings.
    """
    canonical_smiles = []
    for smiles in smiles_list:
        try:
            mol = Chem.MolFromSmiles(smiles)
            if mol:
                canonical = Chem.MolToSmiles(mol, canonical=True)
                canonical_smiles.append(canonical)
            else:
                canonical_smiles.append(None)
        except Exception as e:
            print(f"Error processing SMILES '{smiles}': {e}")
            canonical_smiles.append(None)
    return canonical_smiles

smiles_list = [
    "N1(CCNCC1)C=1C=C(C=CC1)CNC1=CC=C(C=N1)C(=O)N",
    "CC(CNC1=CC=C(C=N1)C(=O)N)(C)C1=CC=CC=C1",
    "NCC=1C=C(C=CC1)C(CNC1=CC=C(C=N1)C(=O)N)(C)C",
    "C1(CC1)C1=CC=2C(=NC=C(C2)C(=O)N)N1CC(=O)N(C1CCNCC1)C",
    "C1(CC1)C1=CC=2C(=NC=C(C2)C(=O)N)N1CC(N1CCNCC1)=O",
    "C(CCCCCCC)NCC1=CC=C(CNC(=O)C2=CSC=3N=CNC(C32)=O)C=C1",
    "C(CCCCCCCCC)NCC1=CC=C(CNC(=O)C2=CSC=3N=CNC(C32)=O)C=C1",
    "C(CCCCCCCCCCC)NCC1=CC=C(CNC(=O)C2=CSC=3N=CNC(C32)=O)C=C1",
    "N1=C(C=CC=C1)NC(=O)C=1C2=C(N=CN1)SC1=C2CCCC1",
    "N1=CC=C(C=C1)NC(=O)C=1C2=C(N=CN1)SC1=C2CCCC1",
    "CC1=CC=CC(=N1)NC(=O)C=1C2=C(N=CN1)SC1=C2CCCC1",
    "CC1=CC(=NC=C1)NC(=O)C=1C2=C(N=CN1)SC1=C2CCCC1",
    "CC=1C(=NC=CC1)NC(=O)C=1C2=C(N=CN1)SC1=C2CCCC1"
]

canonical_smiles = convert_to_canonical_smiles(smiles_list)

with open("canonical_smiles_publications.txt", "w") as file:
    for smiles in canonical_smiles:
        if smiles:
            file.write(smiles + "\n")

print("Canonical SMILES have been written to 'canonical_smiles_publications.txt'")