services:
    db:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: bio
            MYSQL_PASSWORD: bio
            MYSQL_DATABASE: bio
            MYSQL_ROOT_PASSWORD: root
            MYSQL_NATIVE_PASSWORD: ON
        volumes:
            - ./data/db:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10